/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package SHA;

/**
 *
 * @author ASUS2020
 */

// Java program to calculate SHA-1 hash value

import java.io.File;
import java.io.IOException;
import java.math.BigInteger;
import java.nio.file.Files;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Scanner;

public class SHA1 {
    public static String Hash(byte[] input){ //input.getBytes();
        try {
            
            MessageDigest md = MessageDigest.getInstance("SHA-1");  // getInstance() method is called with algorithm SHA-1
            
            byte[] messageDigest = md.digest(input);     // digest() method is called
                                                                    // to calculate message digest of the input string
                                                                    // returned as array of byte
            
            BigInteger no = new BigInteger(1, messageDigest);       // Convert byte array into signum representation
            String hashtext = no.toString(16);                      // Convert message digest into hex value          
            while (hashtext.length() < 32) {                        // Add preceding 0s to make it 32 bit
                    hashtext = "0" + hashtext;
            }
            return hashtext;
        }
        catch (NoSuchAlgorithmException e) {
                throw new RuntimeException(e);
        }
    }


    public static void main(String args[]) throws NoSuchAlgorithmException, IOException{
//        Scanner sc = new Scanner(System.in);
//        System.out.println("Enter a string:");
//        String s1 = sc.nextLine();
//        
//        System.out.println("HashCode Generated by SHA-1: \n"+Hash(s1));
        try{
            File pdf1 = new File("F:\\csattt\\shattered-1.pdf");
            byte[] pdfBytes1 = Files.readAllBytes(pdf1.toPath());
            System.out.println("HashCode shattered-1.pdf: \n"+Hash(pdfBytes1));
            File pdf2 = new File("F:\\csattt\\shattered-2.pdf");
            byte[] pdfBytes2 = Files.readAllBytes(pdf2.toPath());
            System.out.println("HashCode shattered-2.pdf: \n"+Hash(pdfBytes2));
        } 
        catch (Exception e){
            
        }
    }
}

